// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM97NJuhiPs7IOCN0Y15u2x3gPhkY8YD8',
    appId: '1:518328761715:web:77652754b2d3e85632d906',
    messagingSenderId: '518328761715',
    projectId: 'nextmove-69c37',
    authDomain: 'nextmove-69c37.firebaseapp.com',
    storageBucket: 'nextmove-69c37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOvmnYT6rtx95olUoj5loSbE-Oqht_bdg',
    appId: '1:518328761715:android:7ea08f3c9140c21332d906',
    messagingSenderId: '518328761715',
    projectId: 'nextmove-69c37',
    storageBucket: 'nextmove-69c37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDicUnlcYPIR_V3BfIbk-h1ivtZznLQbVw',
    appId: '1:518328761715:ios:31e988fd619420cb32d906',
    messagingSenderId: '518328761715',
    projectId: 'nextmove-69c37',
    storageBucket: 'nextmove-69c37.firebasestorage.app',
    iosBundleId: 'com.example.nextmoveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDicUnlcYPIR_V3BfIbk-h1ivtZznLQbVw',
    appId: '1:518328761715:ios:31e988fd619420cb32d906',
    messagingSenderId: '518328761715',
    projectId: 'nextmove-69c37',
    storageBucket: 'nextmove-69c37.firebasestorage.app',
    iosBundleId: 'com.example.nextmoveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM97NJuhiPs7IOCN0Y15u2x3gPhkY8YD8',
    appId: '1:518328761715:web:a3265901965914a932d906',
    messagingSenderId: '518328761715',
    projectId: 'nextmove-69c37',
    authDomain: 'nextmove-69c37.firebaseapp.com',
    storageBucket: 'nextmove-69c37.firebasestorage.app',
  );
}
