name: Flutter CI

on:
  push:
    branches: [main, dev, 'release/**']
  pull_request:
    branches: [main, dev, 'release/**']

jobs:
  lint:
    uses: ./.github/workflows/flutter_lint.yml
  test:
    uses: ./.github/workflows/flutter_test.yml
    with:
      coverage: true