name: Firebase App Distribution

on:
  workflow_call

jobs:
  # build-and-distribute:
  #   runs-on: ubuntu-latest
  #   env:
  #     TESTER_EMAILS: ${{ secrets.TESTER_EMAILS }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/cache@v4
  #       with:
  #         path: ~/.pub-cache
  #         key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pub-

  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version-file: pubspec.yaml
  #         channel: "stable"
  #         cache: true

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.4'
  #         bundler-cache: true

  #     - name: Set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'temurin'
  #         java-version: '21'

  #     - uses: actions/cache
  #       with:
  #         path: |
  #           ~/.gradle/caches
  #           ~/.gradle/wrapper
  #         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gradle-

  #     - name: Install dependencies
  #       run: |
  #         flutter pub get
  #         bundle install

  #     - name: Build and distribute via Fastlane
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #       run: |
  #         bundle exec fastlane android distribute

  firebase_distribution:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload and Distribute App
        uses: mastersam07/firebase-app-distribution-action@v0.1
        with:
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          file: './build/app/outputs/flutter-apk/app-debug.apk' # change to app-release.apk for release builds
          groups: 'testers'