name: Flutter CI

# Se ejecuta en push o PR a dev y main.
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  # Job para Android
  android-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4' 
        channel: 'stable'

    - run: flutter pub get

    - run: flutter analyze || true  # Ignora exit code, pero logs muestran issues.

    #- run: flutter test  # Tests unitarios.

    # Build APK debug
    - run: flutter build apk --debug

    # Sube el APK como artefacto.
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-android-debug.apk
        path: build/app/outputs/flutter-apk/app-debug.apk

  # Job para iOS (en macOS).
  ios-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'

    - run: flutter pub get

    - run: flutter analyze || true  # Ignora exit code, pero logs muestran issues.

    #- run: flutter test

    # Build iOS debug.
    - run: flutter build ios --debug --no-codesign

    # Sube el Runner.app como artefacto
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-ios-debug
        path: build/ios/iphoneos/Runner.app
