name: Flutter test
on:
  workflow_call:
    inputs:
      coverage:
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV_FILE: ${{ secrets.ENV_FILE }}
    defaults:
      run:
        working-directory: .

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.3"
          channel: "stable"
          cache: true
      - name: Generate test file with all imports to include untested files in coverage
        run: ./.github/workflows/generate_test_with_all_imports.sh
      - name: Create .env file from ENV_FILE secret
        run: echo "$ENV_FILE" > .env
      - name: Run tests with coverage information
        run: flutter test --coverage
      - name: Upload coverage reports for coverage job
        uses: actions/upload-artifact@v5
        with:
          name: coverage
          path: coverage/

  coverage:
      runs-on: ubuntu-latest
      needs: test
      if: ${{ inputs.coverage }}
      permissions:
        contents: read
        pull-requests: write
      steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
      - name: Download coverage reports from test job
        uses: actions/download-artifact@v5
        with:
          name: coverage
          path: coverage/
      - uses: actions/cache@v4
        with:
          path: /usr/local/bin/lcov
          key: lcov-${{ runner.os }}-v1
          restore-keys: |
            lcov-${{ runner.os }}-
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Apply coverage exclusions
        run: lcov --ignore-errors unused,unused --remove coverage/lcov.info '*/main.dart' '*/firebase_options.dart' '*/app_localizations*.dart' '*/graphql/*' '*/presentacion/*' -o coverage/lcov.info
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 0 # The job will pass with no minimum coverage for now
          artifact-name: "" # We skip the artifact upload
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
  # Builds:
  # Para Android: flutter build apk --debug
  # Para iOS: flutter build ios --debug --no-codesign (requiere macos-latest)
