name: Flutter lint
on:
  workflow_call

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"
          cache: true

      # Instala dependencias.
      - run: flutter pub get

      # Verifica el entorno Flutter (como flutter doctor local).
      - run: flutter doctor -v

      # Analiza el código (ignora warnings por ahora).
      - run: flutter analyze || true